services:
  customer-db:
    image: mysql:8.0.36
    container_name: customer-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
    ports:
      - "3308:3306"
    volumes:
      - customer-db-data:/var/lib/mysql

volumes:
  customer-db-data:
